import Link from "next/link";
import { notFound } from "next/navigation";
import { getDict,getServerLocale } from "@/lib/i18n-server";
import { getPrepSubject,listPrepCompetencies,listPrepMaterials } from "@/lib/prep-catalog";
import { EducationOrchestrator } from "@/lib/education/orchestrator";
import type { EducationSearchResult } from "@/lib/education/types";
export const dynamic="force-dynamic";
export default async function PrepSubjectPage({params}:{params:Promise<{program:string;subject:string}>}){
 const {program:programSlug,subject:subjectSlug}=await params; const locale=await getServerLocale(); const t=await getDict(locale); const found=await getPrepSubject(programSlug,subjectSlug); if(!found) notFound();
 const {program,subject}=found; const competencies=await listPrepCompetencies(subject.id); const label=(x:{id?:string;en?:string})=>x[locale]??x.en??x.id??"";
 const dynamicMaterials=new Map<number,EducationSearchResult>();
 await Promise.all(competencies.map(async c=>{try{const q=label(c.title); const r=await new EducationOrchestrator().search({q,page:1,perPage:4,level:[],grade:undefined,subject:[],language:[],resourceType:[],format:[],provider:[],yearFrom:undefined,yearTo:undefined}); dynamicMaterials.set(c.id,r);}catch{}}));
 const linked=await Promise.all(competencies.map(async c=>[c.id,await listPrepMaterials(c.id)] as const)); const linkedMap=new Map(linked);
 return <div className="max-w-5xl mx-auto px-4 py-10 pb-24"><Link href="/persiapan" className="text-sm text-[var(--cf-text-muted)] hover:text-[var(--cf-text)]">← {t.common.back}</Link><header className="pt-6 pb-8"><p className="text-xs uppercase tracking-[0.16em] text-[var(--cf-accent-strong)]">{label(program.title)}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{label(subject.title)}</h1><p className="mt-3 max-w-3xl text-[15px] leading-relaxed text-[var(--cf-text-muted)]">{label(subject.description)}</p></header><div className="mb-6 flex flex-wrap gap-2"><Link href={`/persiapan/${encodeURIComponent(programSlug)}/${encodeURIComponent(subjectSlug)}/latihan`} className="rounded-[10px] bg-[var(--cf-accent)] px-4 py-2 text-sm font-medium text-white">{t.prep.startPractice}</Link><Link href="/persiapan/tryout" className="rounded-[10px] border border-[var(--cf-border)] px-4 py-2 text-sm font-medium">{t.prep.tryoutTitle}</Link><Link href="/persiapan/progress" className="rounded-[10px] border border-[var(--cf-border)] px-4 py-2 text-sm font-medium">{t.prep.progressTitle}</Link></div><div className="space-y-5">{competencies.map(c=>{const ext=linkedMap.get(c.id)??[];const resources=dynamicMaterials.get(c.id)?.resources??[];return <section key={c.id} className="rounded-2xl border border-[var(--cf-border)] p-5"><h2 className="text-lg font-semibold">{label(c.title)}</h2><p className="mt-1 text-sm text-[var(--cf-text-muted)]">{label(c.description)}</p><div className="mt-4 grid gap-2">{ext.map(m=><a key={m.id} href={m.url} target="_blank" rel="noopener noreferrer" className="rounded-lg border border-[var(--cf-border)] px-3 py-2 text-sm hover:border-[var(--cf-accent)]">{label(m.title)} <span className="text-xs text-[var(--cf-text-muted)]">· {m.sourceName??m.resourceType}</span></a>)}{resources.map(r=><a key={r.id} href={r.readUrl??r.sourceUrl??"#"} target="_blank" rel="noopener noreferrer" className="rounded-lg bg-[var(--cf-surface)] px-3 py-2 text-sm hover:text-[var(--cf-accent-strong)]">{r.title} <span className="text-xs text-[var(--cf-text-muted)]">· {r.source}</span></a>)}{ext.length===0&&resources.length===0&&<p className="text-sm text-[var(--cf-text-muted)]">{t.prep.noMaterials}</p>}</div></section>})}</div></div>;
}
