/**
 * Deterministic allowlist sanitizer for HTML generated by the JATS serializer.
 * Text is already HTML-escaped by the serializer; this layer strips forbidden
 * elements/attributes and rejects unsafe URI schemes without jsdom/DOMPurify.
 */

const ALLOWED_TAGS = new Set([
  "p","br","em","i","strong","b","u","sub","sup","span","code","pre","kbd","var","samp",
  "ul","ol","li","blockquote","cite","q","a","abbr","small","h1","h2","h3","h4","h5","h6",
  "table","thead","tbody","tfoot","tr","th","td","caption","colgroup","col","img","figure","figcaption",
  "math","mrow","mi","mo","mn","msup","msub","mfrac","msqrt","mroot","mtext","mspace","mstyle",
  "munder","mover","munderover","mmultiscripts","semantics","annotation","mtable","mtr","mtd","mlabeledtr",
  "mpadded","mphantom","merror"
]);

const ALLOWED_ATTR = new Set(["href","title","alt","src","colspan","rowspan","scope","start","display","encoding","mathvariant"]);
const FORBIDDEN_BLOCKS = /<\/?(?:script|style|iframe|object|embed|form|input|button|svg|link|meta|base)\b[^>]*>[\s\S]*?<\/?(?:script|style|iframe|object|embed|form|input|button|svg|link|meta|base)\s*>/gi;
const FORBIDDEN_SELF = /<\/?(?:script|style|iframe|object|embed|form|input|button|svg|link|meta|base)\b[^>]*\/?>/gi;
const COMMENTS = /<!--[\s\S]*?-->/g;

function unescapeAttr(value: string): string {
  return value.replace(/&quot;/gi, '"').replace(/&#39;/g, "'").replace(/&lt;/gi, "<").replace(/&gt;/gi, ">").replace(/&amp;/gi, "&");
}

function safeUri(value: string): boolean {
  const raw = unescapeAttr(value).trim().replace(/^["']|["']$/g, "");
  return /^(?:https?:|mailto:)/i.test(raw);
}

function sanitizeAttributes(raw: string): string {
  let out = "";
  const attrRe = /([A-Za-z_:][A-Za-z0-9_.:-]*)\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/g;
  let m: RegExpExecArray | null;
  while ((m = attrRe.exec(raw))) {
    const name = m[1].toLowerCase().replace(/^xlink:/, "");
    if (name.startsWith("on") || name === "style" || name === "class" || name === "id" || !ALLOWED_ATTR.has(name)) continue;
    const value = m[2];
    if ((name === "href" || name === "src") && !safeUri(value)) continue;
    out += ` ${name}=${value}`;
  }
  return out;
}

export function sanitizeHtml(dirty: string): string {
  let html = dirty.replace(COMMENTS, "").replace(FORBIDDEN_BLOCKS, "").replace(FORBIDDEN_SELF, "");
  html = html.replace(/<\/?([A-Za-z0-9:-]+)([^>]*)>/g, (full, rawTag: string, rawAttrs: string) => {
    const tag = rawTag.toLowerCase();
    if (!ALLOWED_TAGS.has(tag)) return "";
    if (full.startsWith("</")) return `</${tag}>`;
    const selfClosing = /\/\s*>$/.test(full);
    return `<${tag}${sanitizeAttributes(rawAttrs)}${selfClosing ? " />" : ">"}`;
  });
  return html;
}

export function htmlToText(html: string): string {
  return html
    .replace(/<[^>]*>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&#\d+;/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function safeImageUrl(url: string | null | undefined): string | null {
  if (!url) return null;
  try {
    const u = new URL(url, "https://example.invalid");
    if (u.protocol !== "https:" && u.protocol !== "http:") return null;
    return u.toString();
  } catch {
    return null;
  }
}

export function extractDoi(s: string | null | undefined): string | null {
  if (!s) return null;
  const m = s.match(/10\.\d{4,9}\/[^\s"'<>]+/i);
  return m ? m[0].replace(/[.,;)]+$/, "") : null;
}
