#!/usr/bin/env bash
# Regenerate the Cloudflare real_ip snippet for nginx.
# Cloudflare rotates its edge ranges; re-run this after Cloudflare announces changes.
# Usage: sudo bash scripts/gen_cf_realip.sh
set -euo pipefail

OUT=/etc/nginx/snippets/cloudflare-realip.conf
TMP=$(mktemp)

V4=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4)
V6=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6)

{
  echo "# Cloudflare edge ranges -> trust for real client IP."
  echo "# Generated by scripts/gen_cf_realip.sh on $(date -Iseconds)."
  printf '%s\n' "$V4" | sed '/^[[:space:]]*$/d' | while read -r cidr; do
    echo "set_real_ip_from ${cidr};"
  done
  printf '%s\n' "$V6" | sed '/^[[:space:]]*$/d' | while read -r cidr; do
    echo "set_real_ip_from ${cidr};"
  done
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} >"$TMP"

# Sanity: must contain at least 10 ranges and end with the header directives.
COUNT=$(grep -c '^set_real_ip_from' "$TMP")
if [ "$COUNT" -lt 10 ]; then
  echo "REFUSING: only $COUNT ranges parsed" >&2
  rm -f "$TMP"
  exit 1
fi

install -m 0644 "$TMP" "$OUT"
rm -f "$TMP"
echo "wrote $OUT ($COUNT ranges)"
